import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { randomUUID } from "crypto";
import type { EbookStructure } from "@/types/ebook";
import fs from "fs";
import path from "path";

export const runtime = "nodejs";

// ⚠️ Assure-toi d'avoir NEXT_PUBLIC_OPENAI_API_KEY défini
const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { topic, pages, language, themeId, tone } = body;

    if (!topic || !pages || !language || !themeId) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    const ebookId = randomUUID();

    // Prompt structuré : renvoyer DU JSON STRICT
    const prompt = `
Tu es un générateur de structure d'ebook en format JSON.

### Contraintes :
- Tu dois renvoyer STRICTEMENT du JSON valide.
- Pas de texte avant, pas de texte après.
- Le format EXACT est :
{
  "title": string,
  "subtitle": string,
  "themeId": string,
  "pages": [
    {
      "layout": "cover" | "chapter-intro" | "content-1col" | "content-2cols" | "quote" | "checklist",
      "pageNumber": number,
      "title": string?,
      "subtitle": string?,
      "text": string?,
      "bullets": string[]?,
      "highlight": string?,
      "quoteAuthor": string?,
      "badge": string?
    }
  ]
}

### Règles strictes :
- L'ebook doit avoir EXACTEMENT ${pages} pages.
- La page 1 DOIT être de layout "cover".
- Le sujet global : "${topic}"
- Langue : ${language}
- Ton : ${tone || "professionnel"}
- Aucune page ne doit être vide.
- Aucun HTML, uniquement du texte normal.

Génère maintenant le JSON strict :
`;

    const response = await client.responses.create({
      model: "gpt-4.1-mini",
      input: prompt,
      max_output_tokens: 8000,
    });

    const raw = response.output_text;

    let json: EbookStructure;

    try {
      json = JSON.parse(raw);
    } catch (e) {
      console.error("Erreur JSON IA :", raw);
      return NextResponse.json(
        { error: "Invalid JSON generated by AI", raw },
        { status: 500 }
      );
    }

    // On force le thème choisi par l’utilisateur :
    json.themeId = themeId;

    // Sauvegarde dans /tmp
    const filePath = path.join("/tmp", `${ebookId}.json`);
    fs.writeFileSync(filePath, JSON.stringify(json, null, 2), "utf8");

    return NextResponse.json(
      {
        success: true,
        ebookId, // ➜ utilisé pour print + PDF
      },
      { status: 200 }
    );
  } catch (error: any) {
    console.error("Server error:", error);
    return NextResponse.json(
      { error: "Server error", details: error?.message },
      { status: 500 }
    );
  }
}
