import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { randomUUID } from "crypto";
import type { EbookStructure } from "@/types/ebook";
import fs from "fs";
import path from "path";

export const runtime = "nodejs";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { topic, pages, language, themeId, tone } = body;

    if (!topic || !pages || !language || !themeId) {
      return NextResponse.json(
        { error: "Missing fields" },
        { status: 400 }
      );
    }

    const ebookId = randomUUID();

    const prompt = `
Tu es un générateur de structure d'ebook en format JSON STRICT.

Ne renvoie AUCUN texte avant ou après. UNIQUEMENT un JSON valide.

FORMAT EXACT :
{
  "title": string,
  "subtitle": string,
  "themeId": string,
  "pages": [
    {
      "layout": "cover" | "chapter-intro" | "content-1col" | "content-2cols" | "quote" | "checklist",
      "pageNumber": number,
      "title": string?,
      "subtitle": string?,
      "text": string?,
      "bullets": string[]?,
      "highlight": string?,
      "quoteAuthor": string?,
      "badge": string?
    }
  ]
}

CONTRAINTES :
- EXACTEMENT ${pages} pages
- Page 1 = layout "cover"
- Sujet : "${topic}"
- Langue : ${language}
- Ton : ${tone || "professionnel"}
- AUCUN HTML
- Chaque page doit contenir du contenu

Renvoie maintenant uniquement le JSON.
`;

    const response = await client.responses.create({
      model: "gpt-4.1-mini",
      input: prompt,
      max_output_tokens: 8000,
    });

    const raw = response.output_text;

    // 🔥🔥 FIX : Nettoyage automatique des ```json
    const cleaned = raw
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    let json: EbookStructure;

    try {
      json = JSON.parse(cleaned);
    } catch (e) {
      console.error("JSON invalide généré :", cleaned);
      return NextResponse.json(
        { error: "Invalid JSON generated by AI", raw: cleaned },
        { status: 500 }
      );
    }

    // Remplace themeId par celui choisi par l’utilisateur
    json.themeId = themeId;

    // Sauvegarde serveur temporaire
    const filePath = path.join("/tmp", `${ebookId}.json`);
    fs.writeFileSync(filePath, JSON.stringify(json, null, 2));

    return NextResponse.json(
      { success: true, ebookId },
      { status: 200 }
    );
  } catch (error: any) {
    console.error("Server error:", error);
    return NextResponse.json(
      { error: "Server error", detail: error?.message },
      { status: 500 }
    );
  }
}
