import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { EbookStructure } from "@/types/ebook";

export const runtime = "nodejs";

// ⚠️ Remplace par ta clé
const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    const { topic, pages, language, themeId, tone } = body;

    if (!topic || !pages || !language || !themeId) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Prompt structuré : renvoyer DU JSON STRICT
    const prompt = `
Tu es un générateur de structure d'ebook en format JSON.

### Contraintes
- Tu dois renvoyer STRICTEMENT du JSON valide.
- Pas de texte avant, pas de texte après.
- Format obligatoire :
{
  "title": string,
  "subtitle": string,
  "themeId": string,
  "pages": [
    {
      "layout": "cover" | "chapter-intro" | "content-1col" | "content-2cols" | "quote" | "checklist",
      "pageNumber": number,
      "title": string?,
      "subtitle": string?,
      "text": string?,
      "bullets": string[]?,
      "highlight": string?,
      "quoteAuthor": string?,
      "badge": string?
    }
  ]
}

### Règles
- L'ebook doit avoir EXACTEMENT ${pages} pages.
- La page 1 doit être de type "cover".
- Le contenu doit être cohérent avec le thème : "${topic}".
- Langue : ${language}.
- Ton : ${tone || "professionnel"}.
- Aucune page ne doit être vide.
- Pas de HTML, que du texte brut.

### Génère maintenant le JSON.
    `;

    // Appel OpenAI
    const response = await client.responses.create({
      model: "gpt-4.1-mini",
      input: prompt,
      max_output_tokens: 8000,
    });

    const raw = response.output_text;

    let json: EbookStructure;

    try {
      json = JSON.parse(raw);
    } catch (e) {
      console.error("Erreur JSON:", raw);
      return NextResponse.json(
        {
          error: "Invalid JSON generated by AI",
          raw,
        },
        { status: 500 }
      );
    }

    // Ajout du themeId dans la structure
    json.themeId = themeId;

    return NextResponse.json(
      {
        success: true,
        ebook: json,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "Server error" },
      { status: 500 }
    );
  }
}
